<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: /home/miguel/Escritorio/LATTE_GitHub/Practica 1/public/../app/views/login.latte */
final class Template_8e5ae0ef12 extends Latte\Runtime\Template
{
	public const Source = '/home/miguel/Escritorio/LATTE_GitHub/Practica 1/public/../app/views/login.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Login - Práctica 1</title>
    <style>
        body { font-family: sans-serif; display: flex; justify-content: center; padding-top: 100px; }
        .login-card { border: 1px solid #ccc; padding: 20px; border-radius: 8px; box-shadow: 2px 2px 10px #eee; }
        .error { color: red; }
    </style>
</head>
<body>
    <div class="login-card">
        <h2>Iniciar Sesión</h2>
';
		if ($error) /* line 15 */ {
			echo '        <p class="error">';
			echo LR\Filters::escapeHtmlText($error) /* line 15 */;
			echo '</p>
';
		}
		echo '        <form action="/auth" method="post">
            <p>
                <label>Usuario</label><br>
                <input type="text" name="user" required>
            </p>
            <p>
                <label>Contraseña</label><br>
                <input type="password" name="pass" required>
            </p>
            <button type="submit">Entrar</button>
        </form>
    </div>
</body>
</html>';
	}
}
