<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: /home/miguel/Escritorio/LATTE_GitHub/Practica 1/public/views/index.latte */
final class Template_f8b9850248 extends Latte\Runtime\Template
{
	public const Source = '/home/miguel/Escritorio/LATTE_GitHub/Practica 1/public/views/index.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html>
<head>
    <title>MotorSport JSON Manager</title>
    <style>
        body { font-family: Arial; margin: 2em; }
        .nav { margin-bottom: 20px; background: #f4f4f4; padding: 10px; }
        .cat-block { border: 1px solid #ddd; padding: 10px; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="nav">
        Usuario: <strong>';
		echo LR\Filters::escapeHtmlText($usuario) /* line 13 */;
		echo '</strong> | <a href="/dashboard">Dashboard (Insertar)</a>
    </div>

    <h1>Búsqueda en Mundial</h1>
    <form action="/" method="get">
        <input type="text" name="q" placeholder="Buscar categoría, equipo o piloto..." value="';
		echo LR\Filters::escapeHtmlAttr($busqueda) /* line 18 */;
		echo '">
        <button type="submit">Filtrar</button>
';
		if ($busqueda) /* line 20 */ {
			echo '        <a href="/">Limpiar filtro</a>
';
		}
		echo '    </form>

    <hr>

';
		foreach ($datos as $cat => $equipos) /* line 25 */ {
			echo '    <div class="cat-block">
        <h2>';
			echo LR\Filters::escapeHtmlText($cat) /* line 26 */;
			echo '</h2>
';
			foreach ($equipos as $equipo => $pilotos) /* line 27 */ {
				echo '        <div style="margin-left: 20px;">
            <strong>';
				echo LR\Filters::escapeHtmlText($equipo) /* line 28 */;
				echo ':</strong>
            <ul>
';
				foreach ($pilotos as $p) /* line 30 */ {
					echo '                <li>';
					echo LR\Filters::escapeHtmlText($p) /* line 30 */;
					echo '</li>
';

				}

				echo '            </ul>
        </div>
';

			}

			echo '    </div>
';

		}

		echo '</body>
</html>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['cat' => '25', 'equipos' => '25', 'equipo' => '27', 'pilotos' => '27', 'p' => '30'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
