<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: /home/miguel/Escritorio/LATTE_GitHub/Practica 1/app/config/../views/dashboard.latte */
final class Template_49cd743277 extends Latte\Runtime\Template
{
	public const Source = '/home/miguel/Escritorio/LATTE_GitHub/Practica 1/app/config/../views/dashboard.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html>
<head>
    <title>Dashboard - ';
		echo LR\Filters::escapeHtmlText($usuario) /* line 4 */;
		echo '</title>
</head>
<body>
    <h1>Panel de Control</h1>
    <p>Bienvenido, <strong>';
		echo LR\Filters::escapeHtmlText($usuario) /* line 8 */;
		echo '</strong>.</p>
    
';
		if (!empty($errores)) /* line 10 */ {
			echo '    <div>
        <p>Corrige los siguientes errores:</p>
        <ul>
';
			foreach ($errores as $e) /* line 13 */ {
				echo '            <li>';
				echo LR\Filters::escapeHtmlText($e) /* line 13 */;
				echo '</li>
';

			}

			echo '        </ul>
    </div>
';
		}
		echo '
    <form action="/insertar" method="post">
        <h3>Insertar nuevo objeto</h3>
        <label>Categoría:</label><br>
        <select name="categoria">
            <option value="MotoGP">MotoGP</option>
            <option value="Moto2">Moto2</option>
            <option value="Moto3">Moto3</option>
        </select><br><br>

        <label>Equipo:</label><br>
        <input type="text" name="equipo" placeholder="Ej: Pramac Racing" value="';
		echo LR\Filters::escapeHtmlAttr($equipo ?? '') /* line 27 */;
		echo '"><br><br>

        <label>Piloto y País:</label><br>
        <input type="text" name="piloto" placeholder="Ej: Pecco Bagnaia, Italia" value="';
		echo LR\Filters::escapeHtmlAttr($piloto ?? '') /* line 30 */;
		echo '"><br><br>

        <button type="submit">Guardar en JSON</button>
    </form>

    <p><a href="/">Volver</a></p>
</body>
</html>';
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['e' => '13'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		return get_defined_vars();
	}
}
