<?php

/** Generated by Latte 3.0.24 */

use Latte\Runtime as LR;

/** source: /home/miguel/Escritorio/LATTE_GitHub/Practica 1/app/config/../views/login.latte */
final class Template_39c49dc8dd extends Latte\Runtime\Template
{
	public const Source = '/home/miguel/Escritorio/LATTE_GitHub/Practica 1/app/config/../views/login.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Login - Práctica 1</title>
</head>
<body>
    <div>
        <h2>Iniciar Sesión</h2>
';
		if ($error) /* line 10 */ {
			echo '        <p>';
			echo LR\Filters::escapeHtmlText($error) /* line 10 */;
			echo '</p>
';
		}
		echo '        <form action="/auth" method="post">
            <p>
                <label>Usuario</label><br>
                <input type="text" name="user" required>
            </p>
            <p>
                <label>Contraseña</label><br>
                <input type="password" name="pass" required>
            </p>
            <button type="submit">Entrar</button>
        </form>
    </div>
</body>
</html>';
	}
}
